name: Databricks CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEV_REPO_PATH: "/Workspace/Users/devangbajpai7@gmail.com/CI-CD-DataLemur-Easy-Pyspark (Dev)"
      PROD_REPO_PATH: "/Workspace/Users/devangbajpai7@gmail.com/CI-CD-DataLemur-Easy-Pyspark (Prod)"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - uses: databricks/setup-cli@main

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Configure Databricks CLI
        run: |
          echo "Setting up non-interactive CLI config..."
          export DATABRICKS_CONFIG_FILE=$GITHUB_WORKSPACE/.databrickscfg
          echo "[DEFAULT]" > $DATABRICKS_CONFIG_FILE
          echo "host = ${{ secrets.DEPLOYMENT_URL }}" >> $DATABRICKS_CONFIG_FILE
          echo "token = ${{ secrets.DEPLOYMENT_TOKEN }}" >> $DATABRICKS_CONFIG_FILE

      - name: Deploy Notebooks
        run: |
          if [ "${{ steps.extract_branch.outputs.branch }}" = "dev" ]; then
            echo "Deploying to DEV..."
            databricks repos update "${DEV_REPO_PATH}" --branch "dev" --profile DEFAULT
          elif [ "${{ steps.extract_branch.outputs.branch }}" = "main" ]; then
            echo "Deploying to PROD..."
            databricks repos update "${PROD_REPO_PATH}" --branch "main" --profile DEFAULT
          else
            echo "Branch is neither dev nor main. Skipping deployment."
          fi
