name: CI

on:
  push:
    paths-ignore:
      - .github
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABRICKS_HOST: ${{ secrets.DEPLOYMENT_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
      REPO_PATH: /Workspace/Users/devangbajpai7@gmail.com/CI-CD-DataLemur-Easy-Dev

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - uses: databricks/setup-cli@main

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Git folder
        run: |
          databricks repos update ${{env.REPO_PATH}} --branch "${{ steps.extract_branch.outputs.branch }}"
