name: Databricks CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Databricks CLI (old version)
        run: pip install databricks-cli==0.17.6

      - name: Configure Databricks CLI auth
        run: |
          mkdir -p ~/.databricks
          cat > ~/.databrickscfg <<EOF
          [DEFAULT]
          host = ${{ secrets.DEVELOPMENT_URL }}
          token = ${{ secrets.DEVELOPMENT_TOKEN }}
          EOF

      - name: Deploy to DEV
        run: |
          echo "Deploying all notebooks to DEV..."
          databricks workspace import-dir . "/Workspace/Users/devangbajpai7@gmail.com/CI-CD-DataLemur-Easy-Pyspark (Dev)" --overwrite

      - name: Deploy to PROD
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying all notebooks to PROD..."
          databricks workspace import-dir . "/Workspace/Users/devangbajpai7@gmail.com/CI-CD-DataLemur-Easy-Pyspark (Prod)" --overwrite
